# Generated by Django 3.2.13 on 2022-05-29 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grievance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grievance',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'New'), (2, 'Open'), (3, 'Resolved'), (4, 'Closed')], default=1),
        ),
    ]
