# Generated by Django 4.2.1 on 2023-06-01 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grievance', '0002_auto_20220529_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_grievances', to=settings.AUTH_USER_MODEL),
        ),
    ]
